### PR TITLE
Cythonize voroplusplus.pyx

### PR DESCRIPTION
**Pull request by carlosal1015**
Hi @mmalahe, @kip-hart, thanks for get in touch by email. I propose this upgrade that shows in asciinema.

[asciicast](https://asciinema.org/a/603792)

These are steps to reproduce, with the below files, we can recreate a new `voroplusplus.cpp`. This file will be used to build pyvoro module.

#### `run.sh`

```bash
#!/usr/bin/env bash

# 1/7 system-wide upgrade and install dependencies
sudo pacman -Syu --noconfirm
# 2/7  Install makedependencies
sudo pacman -S --noconfirm cython git
# 3/7 Take the source
cd
git clone https://github.com/mmalahe/pyvoro.git
cd pyvoro
git switch feature/python3.6
# 4/7 Cythonize
pushd pyvoro
cp voroplusplus.cpp voroplusplus.cpp.bak 
cython voroplusplus.pyx --cplus
diff voroplusplus.cpp.bak voroplusplus.cpp
cat voroplusplus.cpp
popd
```

#### `start.sh`

```bash
#!/usr/bin/env bash

docker build -t test .
docker run -ti --rm test /run.sh  2>&1 | tee -a log.log
```

#### `Dockerfile`

```dockerfile
FROM registry.gitlab.com/dune-archiso/images/dune-archiso:latest
COPY ./run.sh /
ENTRYPOINT ["/run.sh"]
```

After these steps, we can build, test and install wheels compatible for python311.

[asciicast](https://asciinema.org/a/603794)

### CODE REVIEW

**Comment by mmalahe** [comment]
Thanks for this. I hit an issue uploading the wheel because PyPI is no longer accepting wheels with the linux_x86_64 platform tag (https://stackoverflow.com/questions/59451069/binary-wheel-cant-be-uploaded-on-pypi-using-twine). I'll switch the build container to one of the suggested manylinux ones and build that out when I find time in the next day or so.

**Comment by carlosal1015** [comment]
> Thanks for this. I hit an issue uploading the wheel because PyPI is no longer accepting wheels with the linux_x86_64 platform tag (https://stackoverflow.com/questions/59451069/binary-wheel-cant-be-uploaded-on-pypi-using-twine). I'll switch the build container to one of the suggested manylinux ones and build that out when I find time in the next day or so.

Great thank you @mmalahe,  please check that is using cython 3 or later.

**Comment by mmalahe** [comment]
Ok, the source distribution and manylinux2014 builds for 3.8-3.11 are up under version 1.3.4. Please let me know if those work fine for you.

**Comment by kip-hart** [comment]
Big kudos to you both @carlosal1015 and @mmalahe! I'm getting all tests passing when I build MicroStructPy in Python 3.8 up to 3.11. ([link](https://github.com/kip-hart/MicroStructPy/actions/runs/5958971410/job/16164005133)) Thank you so much!

**Comment by mmalahe** [comment]
Excellent! And it's a pleasure. @carlosal1015: could you please squash the commits and then I can merge here.

**Comment by carlosal1015** [comment]
> Ok, the source distribution and manylinux2014 builds for 3.8-3.11 are up under version 1.3.4. Please let me know if those work fine for you.

Thank you, [up to date](https://aur.archlinux.org/cgit/aur.git/commit/?h=python-pyvoro-mmalahe&id=ec2cd91cdfb2051f02ae7d5e8c60d99789347d7a) and successful installation.



> Big kudos to you both @carlosal1015 and @mmalahe! I'm getting all tests passing when I build MicroStructPy in Python 3.8 up to 3.11. ([link](https://github.com/kip-hart/MicroStructPy/actions/runs/5958971410/job/16164005133)) Thank you so much!

Great, we did it!

**Comment by carlosal1015** [comment]
> Excellent! And it's a pleasure. @carlosal1015: could you please squash the commits and then I can merge here.

Thanks @mmalahe, done.

**Pull request merged**
